#spring.data.mongodb.uri= mongodb://localhost:18000/dbcustomer

#spring.application.name=servicio-customers
#server.port:8080
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

server:
  port: 8080
  servlet:
    application-display-name: servicio-customers

datasource:
  url: mongodb://localhost:18000/dbcustomer
  
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka
      